version: '3'
services:
    consul:
        image: consul:1.0.2
        command: consul agent -dev -ui -client 0.0.0.0
        ports:
        - 8300:8300
        - 8500:8500
        - 8600:8600
    app:
        build: .
        ports:
        - 8080:8080
        volumes:
        - ./configs/application.yml:/tmp/application.yml
