---
spring:
    application:
        name: compose-testapp
    profiles: 
        active: docker
    cloud:
        consul:
            host: consul
            port: 8500
            discovery:
                instanceId: ${spring.application.name}:${random.value}
                healthCheckPath: /actuator/health
                #healthCheckPath: ${management.context-path}/health
                healthCheckInterval: 15s

management:
    endpoints:
        web:
            exposure:
                include: 
                    -   env
                    -   health
                    -   info
